### ISSUE TITLE
关于新版开发的一些问题

### ISSUE THREAD

**Issue by mahoshojoHCG** [HCGStudio/HIT-Schedule-Master-Plus#1]
由于最近开的课程比较多，尤其是某些课程要写十分多的代码，再加上假期咕的比较多，所以这个版本的开发**十分缓慢**。
但是我们并不忍心抛弃这个项目，因此我们决定将功能模块化，分期施工，并且一周**至少**实现一个功能。
第一周将实现手动从教务系统下载Excel格式的课表，然后进行转换的功能。
以下的功能需要大家的投票，来决定功能实现的先后顺序：

1. 通过填写用户名、密码、验证码自动下载课表
2. 对于已添加的课程，实现手动的增添与修改。
3. 能够以`Json`的格式导入导出课表，供储存以及恢复。
4. 对于即将开始的课程，能在应用内进行推送，而不依赖于导出的日历。
5. （需要4为基础）建立服务器，能够在课表程序不常驻后台的情况下进行课程推送。
6. 开发移动版应用。（鉴于Android平台已经有应用，这里会`iOS`平台优先，这可能会消耗2周或更久）
7. （需要6为基础）为移动端应用建立推送。

要进行投票，在下面回复序号即可。

或者，你有什么好的建议，也可以单独开一个issue进行功能请求，我们会按照功能的重要性以及想要的人数进行开发。

**Comment by RiverShi** [comment]
6
