### ISSUE TITLE
读取时显示项目文件已卸载

### ISSUE THREAD

**Issue by Hanbinbinbin** [HCGStudio/HIT-Schedule-Master-Plus#3]

**Comment by roller-skating** [comment]
弹出窗口：“未能正确加载解决方案中的一个或多个项目。有关详细信息，请参加输出窗口”

**Comment by mahoshojoHCG** [comment]
是否已经正确安global.json内指定的dotnet版本?是否安装Electron.Net环境?并且请提供输出窗口的内容。
